# Generated by Django 5.1.2 on 2024-10-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_toy_alter_feeding_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="toys",
            field=models.ManyToManyField(to="main_app.toy"),
        ),
    ]
